### ISSUE TITLE
Will you make the scraping results available?

### ISSUE THREAD

**Issue by jafl** [Pixelz22/InfiniteCraft#1]
I would like to make a graph ui, so I can study all the ways a particular object can be created and thereby learn what the ai has learned about culture.

**Comment by Pixelz22** [comment]
Hey there @jafl 

I've recently decided to merge this project with that of a friend of mine, @quantumbagel. We're gonna be collaborating to turn this into a public website with multiple features, including a most-optimal crafting tree finder. The new repository is [here](https://github.com/FiniteCraft/FiniteCraft). The scraping data will almost definitely be public. You're free to access it when you want to.
